### ISSUE TITLE
TypeError: nil is not a symbol

### ISSUE THREAD

**Issue by joergrech** [vossim/dashing-jira-burndown#7]
After installing and configuring the data in the ruby job file I get the following error after starting dashing:

```
bundler: failed to load command: thin (/usr/local/bin/thin)
TypeError: nil is not a symbol
  /Users/jorgrech/repos/Dashing/dashboard-tech/jobs/jira_burndown.rb:29:in `private'
  /Users/jorgrech/repos/Dashing/dashboard-tech/jobs/jira_burndown.rb:29:in `<class:SprintJsonDownloader>'
  /Users/jorgrech/repos/Dashing/dashboard-tech/jobs/jira_burndown.rb:22:in `<top (required)>'
  /Library/Ruby/Gems/2.0.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
  /Library/Ruby/Gems/2.0.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
  /Library/Ruby/Gems/2.0.0/gems/dashing-1.3.6/lib/dashing/app.rb:171:in `block in require_glob'
  /Library/Ruby/Gems/2.0.0/gems/dashing-1.3.6/lib/dashing/app.rb:170:in `each'
  /Library/Ruby/Gems/2.0.0/gems/dashing-1.3.6/lib/dashing/app.rb:170:in `require_glob'
  /Library/Ruby/Gems/2.0.0/gems/dashing-1.3.6/lib/dashing/app.rb:181:in `<top (required)>'
  /Library/Ruby/Gems/2.0.0/gems/dashing-1.3.6/lib/dashing.rb:3:in `require'
  /Library/Ruby/Gems/2.0.0/gems/dashing-1.3.6/lib/dashing.rb:3:in `<top (required)>'
  config.ru:1:in `require'
  config.ru:1:in `block in <main>'
  /Library/Ruby/Gems/2.0.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
  /Library/Ruby/Gems/2.0.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /Library/Ruby/Gems/2.0.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
  /Library/Ruby/Gems/2.0.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
  /Library/Ruby/Gems/2.0.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
  /Library/Ruby/Gems/2.0.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
  /Library/Ruby/Gems/2.0.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
  /Library/Ruby/Gems/2.0.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
  /usr/local/bin/thin:23:in `load'
  /usr/local/bin/thin:23:in `<top (required)>'
```

**Comment by vossim** [comment]
Hi @joergrech are you using point or time-based burn-downs? This plugin currently only works with time-based burn-downs.
